IF OBJECT_ID('dbo.UserRoles', 'U') IS NOT NULL
    DROP TABLE UserRoles
IF OBJECT_ID('dbo.Roles', 'U') IS NOT NULL
  DROP TABLE Roles
GO

CREATE TABLE Roles (
  RoleID INT PRIMARY KEY NOT NULL IDENTITY,
  RoleName NVARCHAR(45) NOT NULL
);
GO

CREATE TABLE UserRoles (
  UserRoleID INT PRIMARY KEY NOT NULL IDENTITY,
  UserID INT NOT NULL,
  RoleID INT NOT NULL,
  CONSTRAINT FK_UserRoles_AuthUser FOREIGN KEY (UserID) REFERENCES AuthUser (UserID),
  CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleID) REFERENCES Roles (RoleID)
);
GO

INSERT INTO Roles (RoleName) VALUES ('ADMIN');
INSERT INTO Roles (RoleName) VALUES ('SERVICEMAN');
INSERT INTO Roles (RoleName) VALUES ('WORKER');
GO

INSERT INTO UserRoles (UserID, RoleID) VALUES (1, 1);
INSERT INTO UserRoles (UserID, RoleID) VALUES (2, 2);
INSERT INTO UserRoles (UserID, RoleID) VALUES (3, 3);
INSERT INTO UserRoles (UserID, RoleID) VALUES (4, 3);
GO